[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ssuai/Hands-On-Large-Language-Models/blob/main/chapter02/lab_2_2_embeddings.ipynb)

### [OPTIONAL] - Installing Packages on Colab

If you are viewing this notebook on Google Colab (or any other cloud vendor), you need to **uncomment and run** the following codeblock to install the dependencies for this chapter:

---

💡 **NOTE**: We will want to use a GPU to run the examples in this notebook. In Google Colab, go to
**Runtime > Change runtime type > Hardware accelerator > GPU > GPU type > T4**.

---

In [2]:
%%capture
!pip install --upgrade transformers==4.41.2 sentence-transformers==3.0.1 gensim==4.3.3 scikit-learn==1.5.0 accelerate==0.31.0 peft==0.11.1

# Contextualized Word Embeddings From a Language Model (Like BERT)

In [3]:
from transformers import AutoModel, AutoTokenizer

# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

# Load a language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

# Tokenize the sentence
tokens = tokenizer('Hello world', return_tensors='pt')

# Process the tokens
output = model(**tokens)[0]

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:
output.shape

torch.Size([1, 4, 384])

In [5]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
Hello
 world
[SEP]

In [6]:
output

tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)

# Text Embeddings (For Sentences and Whole Documents)

In [21]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [8]:
vector.shape

(768,)

In [20]:
vector

array([-2.02203933e-02,  4.57696877e-02, -1.26637146e-02, -3.37991631e-03,
       -2.54910300e-03, -3.31096235e-03, -4.58366945e-02,  2.32390799e-02,
       -3.12585123e-02, -3.15588824e-02, -2.19783355e-02,  3.67821753e-03,
        3.39105981e-03, -1.88130587e-02, -2.65821870e-02, -1.45892315e-02,
        3.20066400e-02, -3.66493082e-03,  1.75410733e-02,  5.43209612e-02,
       -3.96661647e-02,  9.93637647e-03, -3.27205285e-02, -1.62909944e-02,
        6.36525359e-03, -1.24459760e-02,  1.04737049e-02,  3.08674313e-02,
        7.47453189e-03, -3.86319868e-02, -6.19924963e-02, -3.25308628e-02,
       -1.40268244e-02,  5.16586639e-02,  1.69651707e-06, -1.74092929e-04,
       -1.27881172e-03, -4.15052772e-02,  5.00347884e-03,  4.58600894e-02,
       -2.85337027e-02,  5.02370670e-02, -1.75183658e-02, -3.98830482e-04,
        1.63311344e-02,  5.89936748e-02, -2.21730098e-02, -4.00975086e-02,
       -6.60439581e-03, -2.97632981e-02, -3.18221636e-02, -1.77945811e-02,
       -1.54363075e-02, -3.44515145e-02,  6.25759885e-02,  2.34393147e-03,
        3.44157927e-02, -8.25463980e-03,  7.44929984e-02, -3.81285027e-02,
       -6.80808499e-02, -4.23289910e-02, -1.83171872e-02, -2.44084150e-02,
        1.99337862e-02, -2.06878185e-02,  2.39973180e-02,  3.49854454e-02,
       -6.95872083e-02,  4.31548096e-02,  1.57101005e-02, -4.87711793e-03,
        6.38265833e-02,  2.81548090e-02,  5.08512557e-02, -2.83363927e-02,
       -4.60657030e-02,  6.47140667e-02,  6.61476776e-02, -2.46198773e-02,
       -6.05491884e-02, -3.04247695e-03,  6.28792271e-02,  2.83486359e-02,
        5.71174584e-02,  6.52741082e-03, -6.45669829e-03,  1.11733014e-02,
        2.18259897e-02, -1.60585195e-02,  3.98896402e-03, -2.04675854e-03,
        3.96747794e-03,  4.18877304e-02, -2.90661119e-02, -4.19957861e-02,
        4.34482507e-02,  4.26485986e-02,  7.53285224e-03, -3.28948610e-02,
       -8.28769710e-03,  2.01881062e-02,  1.37378471e-02,  1.38777867e-02,
        4.24899198e-02,  2.69807577e-02, -1.83730442e-02, -3.71770225e-02,
        3.31590399e-02,  2.42859237e-02, -3.89447063e-02,  2.28922558e-03,
        5.35068810e-02,  6.79784343e-02, -9.70004778e-03, -6.89618476e-03,
        8.24520290e-02, -4.85090818e-03, -1.19632296e-02,  1.12272035e-02,
       -1.84042715e-02, -9.23727453e-03, -2.06847563e-02,  2.53276452e-02,
       -1.11306412e-02, -4.08682693e-03, -2.30704453e-02, -2.89186090e-02,
        4.45920080e-02, -3.02654877e-03, -4.13768142e-02,  5.19979224e-02,
        4.95345984e-03, -6.28711730e-02,  3.07494309e-02,  4.33228016e-02,
       -2.99513545e-02, -2.41307449e-03,  3.73286679e-02, -4.21258714e-03,
        3.35870720e-02, -4.57396507e-02, -7.57045224e-02, -1.43684756e-05,
        3.77049595e-02,  1.17524620e-02,  6.80495985e-03, -2.76920409e-03,
        2.55940072e-02, -4.55860943e-02,  3.38432379e-02, -2.46408060e-02,
       -1.58957932e-02, -9.64216329e-03, -1.74004771e-02,  1.95757244e-02,
       -1.72167104e-02, -4.00132090e-02,  8.84149689e-03,  5.63180353e-03,
       -5.64631969e-02,  4.18704115e-02,  6.14107735e-02, -2.33447626e-02,
       -6.02262095e-02,  2.65606977e-02, -8.73995200e-03, -2.54318379e-02,
       -5.78650385e-02, -1.63434097e-03, -3.57385986e-02,  8.78338423e-03,
       -1.86853390e-02, -2.27693394e-02, -1.64402947e-02,  9.16428631e-04,
       -2.75907898e-03, -2.11251900e-02,  1.17958141e-02,  6.54988289e-02,
       -1.34429233e-02, -5.85037423e-03, -2.26886012e-02, -4.69197286e-03,
       -6.56697247e-03, -5.58430329e-03, -2.37320680e-02,  2.63373158e-03,
        2.79200003e-02,  1.75014045e-02,  7.05148876e-02,  2.04410125e-03,
        3.96886282e-02, -7.11207092e-03, -5.53246308e-03, -1.76759232e-02,
       -9.80818272e-03,  4.24953224e-03,  5.34049720e-02,  7.13995770e-02,
        1.45237753e-02,  6.63722865e-03,  1.84459947e-02, -3.81757095e-02,
       -1.90554801e-02, -5.48273697e-02, -1.84071399e-02, -4.95261177e-02,
       -4.00508195e-02,  8.68849643e-03, -2.48502679e-02,  4.53157797e-02,
        2.03235913e-02, -3.21139432e-02,  1.56295951e-02,  3.62752452e-02,
        6.59925416e-02,  3.26601714e-02, -8.78327340e-02,  9.44340378e-02,
        2.16405299e-02, -8.00879672e-03, -5.13045350e-03,  1.49670215e-02,
       -9.37998481e-03, -1.62820499e-02, -8.78320774e-04, -2.41658222e-02,
        7.28241578e-02,  5.06999791e-02, -7.54109398e-03,  2.89575569e-02,
        6.94771558e-02, -3.20686027e-02,  8.36075842e-03,  2.72288937e-02,
        4.86845113e-02,  2.09293272e-02, -4.85207234e-03, -1.35733664e-01,
        5.91989122e-02,  3.52462716e-02, -3.54933040e-03,  5.53833973e-03,
       -7.42449518e-03, -1.85083300e-02, -2.47552469e-02,  3.68198045e-02,
        4.10624668e-02,  4.83447267e-03, -5.03981188e-02, -7.56619591e-03,
       -7.34616742e-02, -1.37477014e-02, -4.96551245e-02, -5.77377267e-02,
        2.30375994e-02,  1.72316469e-02, -1.10098580e-02, -5.00851125e-03,
        3.73133495e-02, -1.22196749e-02,  3.67945582e-02,  3.23757976e-02,
        3.03839371e-02,  3.12438328e-02,  1.34678390e-02,  2.09658570e-03,
        9.05989576e-03,  3.20697799e-02,  4.30423208e-02,  1.61133949e-02,
       -1.97642460e-03,  4.51487042e-02, -2.61757709e-03, -2.10353751e-02,
        1.23143913e-02,  2.19331235e-02, -7.48108029e-02, -1.87374800e-02,
        5.77959465e-03, -1.66843254e-02,  3.49258073e-02,  1.69625469e-02,
       -1.29547454e-02,  2.42918115e-02,  1.33142387e-02, -6.13087881e-03,
        1.24595780e-02, -6.53126761e-02, -1.60474386e-02, -4.14024517e-02,
        3.02160103e-02,  3.15759704e-02,  2.17898488e-02,  9.32294317e-03,
       -6.24404289e-02, -2.23614611e-02, -5.48126772e-02, -7.60867372e-02,
       -4.92595285e-02,  3.03733293e-02, -1.11720944e-03, -2.49408446e-02,
        4.89794947e-02, -2.57986244e-02, -4.59413677e-02, -8.69544595e-03,
       -1.24728670e-02,  2.25808118e-02, -2.81890985e-02,  5.30083776e-02,
       -8.50981176e-02, -1.57342628e-02, -2.83088740e-02,  1.50961336e-02,
       -3.79612530e-03, -6.45769387e-02,  2.63364166e-02,  3.87118943e-02,
       -4.34800837e-04, -1.71438567e-02, -3.64410654e-02,  2.42590960e-02,
       -2.05201674e-02,  1.98235959e-02,  3.23042460e-02, -5.71228098e-03,
        4.89671007e-02,  1.66042447e-02, -3.73701518e-03, -3.16586159e-02,
        5.87326102e-02, -3.70643139e-02, -9.46529489e-03,  1.18760224e-02,
       -5.57537563e-02, -2.59902980e-02, -7.00723305e-02,  4.13720235e-02,
        9.44955274e-03,  8.65642820e-03, -2.11738069e-02, -3.13928574e-02,
       -4.39831167e-02, -2.41709575e-02, -6.17116727e-02, -7.56191239e-02,
       -2.43743472e-02,  5.23749664e-02,  9.59643163e-03,  2.09737048e-02,
       -5.92924189e-03,  2.82215443e-03,  2.52180472e-02, -5.18826209e-03,
       -2.51272712e-02, -2.08315048e-02, -1.32330898e-02, -2.14497708e-02,
        4.04742826e-03,  2.10041758e-02,  2.12136758e-04,  4.75079268e-02,
        6.97088912e-02, -1.95958316e-02, -5.54395095e-02,  3.15217674e-02,
        1.19435005e-02, -3.56129184e-02, -4.14416147e-03, -1.77258800e-03,
       -6.62559196e-02,  3.22466716e-02, -2.87152734e-02, -2.36792732e-02,
       -1.68481879e-02, -1.88505854e-02, -1.20192971e-02,  7.31911350e-05,
        3.12584750e-02,  4.72692511e-04, -6.26352336e-03, -3.22463028e-02,
       -2.92952191e-02,  2.90423017e-02, -1.47413081e-02,  2.43108682e-02,
       -1.26742879e-02,  7.43110403e-02,  6.77752793e-02, -6.38445048e-03,
       -8.33843742e-03,  5.84004819e-03,  3.46759036e-02, -7.89596140e-03,
       -9.79571138e-03, -3.47787142e-02, -5.03329784e-02, -6.80282339e-03,
       -2.32676347e-03,  1.63682789e-01,  3.31020169e-02,  7.22550228e-02,
        6.55808523e-02, -4.43043333e-04,  7.60614574e-02,  3.29805426e-02,
       -2.50527374e-02,  4.97032003e-03, -7.38654171e-06,  1.77387265e-03,
       -4.73156683e-02,  1.24155749e-02, -1.79417282e-02, -3.96828633e-03,
       -1.64653491e-02, -4.98488396e-02, -4.93970960e-02, -1.77263599e-02,
       -5.79475006e-03,  5.12049235e-02,  6.15338311e-02, -2.02965941e-02,
        4.10276316e-02,  7.97440484e-03,  1.60987803e-03,  2.73898710e-03,
        2.56859008e-02,  3.49121317e-02,  3.48256230e-02,  2.99326237e-02,
       -2.05292590e-02, -3.16914469e-02, -4.00760025e-03, -6.82935789e-02,
        2.53672581e-02,  1.60931889e-02,  3.90187162e-03, -1.00664597e-03,
       -4.16302457e-02,  2.39275806e-02,  1.93549804e-02,  8.67202040e-03,
       -4.15938906e-02, -2.54745446e-02, -2.57343352e-02, -2.41257269e-02,
        1.68336637e-03, -1.94083794e-03, -1.33337395e-03, -2.77865548e-02,
        9.17965733e-03, -5.63236326e-02,  6.82892948e-02,  2.38570422e-02,
        3.62705924e-02, -9.64243058e-03,  2.39587370e-02,  2.71281824e-02,
        9.78971645e-02,  3.71735543e-02,  1.77358259e-02, -4.09085974e-02,
        5.76262102e-02,  4.53530103e-02, -7.39419460e-03, -1.50913429e-02,
        1.35779465e-02, -3.29060666e-02, -2.47587990e-02, -1.26152241e-03,
        6.75930083e-03, -1.91760156e-02, -6.33706525e-03, -7.85872638e-02,
        2.50525251e-02, -9.13120508e-02,  3.05409934e-02, -2.07534079e-02,
       -6.91620680e-03, -1.69424526e-03,  1.80584770e-02, -9.01445094e-03,
        6.07968643e-02, -7.59931430e-02, -3.42037231e-02,  2.36437563e-02,
       -6.94918353e-03,  1.95292700e-02, -6.66128239e-03, -4.78449278e-03,
       -1.23866796e-02, -2.50967946e-02, -6.64266571e-02, -3.37183028e-02,
        2.51410492e-02, -4.08467799e-02,  6.33136034e-02, -1.46272816e-02,
        1.37926359e-02,  8.56989529e-03, -2.74824593e-02,  8.24874043e-02,
       -3.33504975e-02, -1.88082568e-02,  1.64880939e-02,  2.23316159e-02,
       -2.33952701e-02, -1.54915219e-02,  1.58764459e-02,  1.32024754e-02,
       -3.13520543e-02, -3.49490307e-02,  4.14551497e-02,  2.04285122e-02,
       -4.56376784e-02, -6.66560903e-02, -1.16886077e-02,  2.10027546e-02,
        9.88319609e-03, -6.19188743e-03, -4.83619235e-02,  2.68509388e-02,
        1.07400306e-02, -1.21475989e-03,  3.40227894e-02, -4.31524124e-04,
        7.58250058e-02,  1.72219425e-02, -1.55712496e-02,  1.66772178e-03,
        9.24157798e-02,  1.51795149e-02, -4.27686945e-02,  1.10518157e-01,
        2.41131894e-02,  2.22330983e-03,  1.09922076e-02,  1.45182414e-02,
       -5.40817380e-02, -2.92328373e-03, -1.81706175e-02, -6.50135195e-03,
        8.84762779e-02, -4.08634394e-02, -2.46939342e-02, -5.75011130e-03,
       -3.22964489e-02, -2.96047144e-02,  1.49137222e-05,  6.85951812e-03,
        1.28585938e-02, -8.72276817e-03, -1.48365367e-02, -7.02032483e-33,
       -4.22567595e-03, -7.70923719e-02, -6.34928793e-03,  1.88374221e-02,
       -1.08135216e-01,  6.80679129e-03,  1.62729900e-02,  1.74700040e-02,
       -3.21586318e-02, -1.56158803e-03, -1.21567016e-02,  1.36200022e-02,
        2.77593508e-02, -9.20705032e-03, -4.14166860e-02, -2.56593004e-02,
       -1.12560717e-02,  4.94263731e-02, -2.78257788e-03,  9.62432823e-04,
        4.10978645e-02,  2.60312241e-02,  4.17773426e-02,  1.70261078e-02,
       -3.55316401e-02,  3.93776000e-02, -8.13048631e-02,  2.14783987e-03,
        6.34985417e-02,  3.19656804e-02,  5.42129427e-02,  2.19822599e-04,
       -1.19869569e-02, -4.00769487e-02,  6.91371709e-02, -2.37348229e-02,
        1.84541736e-02,  5.91237806e-02, -1.81721747e-02, -3.54840606e-02,
       -7.07990304e-02, -3.47007439e-02,  2.24273140e-03, -6.55507669e-02,
       -3.94935161e-02,  1.90424826e-02, -1.63912624e-02,  4.02781591e-02,
        3.14998999e-03,  1.21332295e-02, -6.33518249e-02, -6.07376872e-03,
       -1.06719881e-02, -9.25485343e-02, -1.00543974e-02, -3.12487502e-02,
       -1.62011422e-02,  1.15962746e-02, -7.22086504e-02,  3.07977013e-02,
       -4.02981453e-02, -4.38704863e-02,  7.42036663e-03, -1.51422760e-02,
       -9.55196004e-03,  3.73821557e-02,  5.66349402e-02, -8.54413863e-03,
        4.58098919e-04, -3.60886753e-02, -6.04565740e-02, -4.95448243e-03,
       -1.58476252e-02, -3.05459765e-03,  4.35595885e-02, -3.49933505e-02,
       -8.74718130e-02, -2.11460795e-02,  4.69010621e-02,  1.14765333e-03,
       -9.70445573e-03,  1.26246447e-02,  3.87018472e-02,  1.04797520e-02,
        3.05910818e-02, -4.95134760e-03, -2.14421842e-02,  1.85080282e-02,
       -4.06456590e-02,  9.62910417e-04, -7.90949985e-02, -1.98711902e-02,
       -6.67678518e-03, -1.66491792e-02,  2.22318601e-02, -6.31384403e-02,
       -2.61658058e-02, -5.00156358e-02, -1.82533059e-02,  2.92074904e-02,
        8.58040228e-02, -1.85399279e-02, -2.01680083e-02,  5.81668355e-02,
        9.49720219e-02,  8.68616998e-03, -1.10520404e-02, -2.13644784e-02,
        1.17103793e-02, -1.38579179e-02,  1.19232610e-02,  2.64743175e-02,
       -2.23848801e-02,  1.22761849e-04, -3.45518775e-02,  2.53635067e-02,
        3.13297734e-02,  4.28087637e-02,  2.94206366e-02, -1.82315130e-02,
        1.32388044e-02,  3.09947934e-02, -9.06949192e-02,  1.72532257e-02,
       -1.94001477e-02,  3.73058803e-02,  2.29968149e-02, -7.08247796e-02,
       -1.39049655e-02, -9.68997250e-04,  1.17215859e-02, -7.10179061e-02,
        2.51297138e-07, -1.39412927e-02,  7.07557565e-03, -8.92848615e-03,
        1.10410377e-02,  1.87252890e-02,  2.12269109e-02, -2.81214714e-02,
        2.27614231e-02,  3.69848572e-02, -5.49838925e-03, -4.84631434e-02,
        7.79398978e-02, -1.73098668e-02,  2.15901509e-02,  2.86326613e-02,
        4.03626543e-03,  4.57128659e-02, -1.19320430e-01, -2.15146989e-02,
        4.14245063e-04, -3.48097784e-03, -3.38213854e-02, -2.95485687e-02,
        5.80028892e-02, -5.94564155e-02, -3.89758833e-02,  8.25334061e-03,
        1.70042943e-02, -7.95115158e-03, -7.65293185e-03, -5.41230710e-03,
        1.79018863e-02,  2.96021812e-02,  6.20511062e-02, -4.05569372e-05,
       -7.20464289e-02,  4.25473042e-02,  2.78940164e-02, -5.75263165e-02,
        6.42126724e-02, -4.63280566e-02,  2.45123059e-02, -3.43407132e-02,
        2.65387427e-02, -2.71380953e-02,  3.75326462e-02,  1.25607708e-02,
       -2.84883427e-03, -2.97331791e-02,  1.33428006e-02,  6.07454255e-02,
        1.28926858e-02, -4.96661961e-02,  4.94489037e-02,  1.42552759e-02,
        3.98472510e-02,  5.44130914e-02,  1.44855380e-02,  1.88953504e-02,
       -2.00763438e-02, -9.07154195e-03, -1.45998551e-02,  5.59374131e-03,
        2.16930751e-02, -3.94869857e-02, -3.72502655e-02, -2.90760975e-02,
        1.47246038e-34,  7.02328384e-02, -2.57433522e-02,  7.10346177e-02,
       -1.78425666e-02,  1.64556261e-02,  3.00991517e-02,  5.60350390e-03,
        9.69089102e-03,  6.91118911e-02, -1.28524033e-02, -5.07157063e-03],
      dtype=float32)

In [23]:
vector2 = model.encode("I watched the movie One Battle After Another last weekend. It was the best movie ever!")
vector2

array([-2.67506428e-02,  5.06745875e-02,  1.52687719e-02,  3.46124731e-02,
        2.63262745e-02, -1.36933671e-02, -4.17678170e-02,  5.22871222e-03,
       -7.65343234e-02, -1.31951850e-02, -7.50181377e-02, -6.53573358e-03,
       -1.66906056e-03, -2.04616580e-02,  2.87406668e-02,  2.48090131e-04,
        5.69002144e-02, -2.56392229e-02, -5.40490709e-02,  3.78300026e-02,
        1.43145369e-02, -4.81950343e-02,  3.43623571e-03, -4.29103710e-02,
       -2.04771403e-02,  3.15443762e-02, -1.72283780e-02, -1.39464475e-02,
        6.31325543e-02, -9.94180739e-02,  3.74041200e-02, -8.08880925e-02,
        2.37063672e-02,  8.99729207e-02,  1.04875960e-06, -4.53571491e-02,
        5.67712472e-04, -8.82114936e-03,  1.50912302e-02,  5.11959307e-02,
       -6.14833739e-03,  4.49514575e-02, -6.04041815e-02, -8.00653771e-02,
        3.92423831e-02,  1.44530507e-02,  1.12929279e-02,  6.08630069e-02,
       -2.11280398e-03, -5.59169836e-02, -4.00140276e-03, -2.84913313e-02,
        4.86506820e-02,  5.32003352e-03, -3.68316378e-03,  4.82078157e-02,
       -1.87441334e-02, -3.51304114e-02,  6.94540516e-02, -9.65609774e-03,
       -2.90929582e-02, -1.77938566e-02,  2.14337241e-02, -8.67250934e-03,
        2.97810254e-03, -8.08312092e-03, -1.14389500e-02,  8.28245506e-02,
       -6.97080418e-02,  4.44310568e-02,  1.86818577e-02, -3.17581906e-03,
       -6.57815894e-04,  1.93035156e-02,  2.79798843e-02, -3.97079028e-02,
       -5.41645586e-02, -2.12762883e-04,  5.55435978e-02,  1.54759306e-02,
       -1.31496007e-03,  4.99784946e-03,  3.42713259e-02, -5.49646318e-02,
        4.44303788e-02,  2.04784051e-02, -1.48411933e-02, -1.47593711e-02,
       -5.93637489e-03,  1.10781277e-02,  8.97751714e-04,  2.71364003e-02,
       -3.98746738e-03,  5.15037142e-02, -6.19368628e-03, -2.54462678e-02,
       -6.65290561e-03,  1.63607318e-02,  4.65136440e-03, -4.55334671e-02,
        4.86887107e-03, -3.61224897e-02, -3.14509496e-02,  3.20263281e-02,
        2.58834865e-02,  8.27958062e-02,  2.50071343e-02, -1.77121926e-02,
        6.63071647e-02,  4.01038043e-02, -4.75612208e-02,  7.46017686e-05,
        2.83131041e-02,  8.16290751e-02,  2.29153801e-02, -4.75149527e-02,
        7.05164075e-02, -5.39078265e-02, -2.07225755e-02,  1.19183713e-03,
       -2.04311162e-02, -2.87091918e-02,  2.16933228e-02, -1.02256006e-02,
       -3.69293988e-02,  1.21705225e-02, -4.02549617e-02, -4.07169275e-02,
        5.71732968e-03, -2.79121455e-02, -5.77334389e-02,  3.80906984e-02,
       -5.43590002e-02, -1.43337669e-02, -1.86381806e-02, -1.60954390e-02,
       -3.73441391e-02, -1.30780395e-02,  1.68248713e-02, -1.28404312e-02,
       -3.74914296e-02, -9.46181361e-03, -2.58067455e-02,  1.02978293e-02,
        6.22984804e-02, -2.62392089e-02,  1.43509288e-03,  2.05244366e-02,
        5.40766213e-03, -5.28954379e-02,  8.68056267e-02, -6.78769732e-03,
       -1.12736300e-02,  2.96899192e-02, -4.40264158e-02, -4.61059213e-02,
        2.47207470e-04, -3.70970964e-02,  2.91107222e-02,  5.59536368e-03,
       -7.06291897e-03,  6.32169023e-02, -2.44043279e-03,  6.17886744e-02,
       -3.55357714e-02, -1.97942983e-02, -6.51598796e-02,  4.38073324e-03,
       -1.27315717e-02,  2.80490164e-02,  9.06893332e-03,  1.68573018e-02,
       -3.88466157e-02, -7.77344108e-02, -8.68158508e-03, -8.40989724e-02,
       -4.77742404e-02, -2.95363534e-02, -1.79557260e-02,  2.99147666e-02,
        5.94858974e-02,  5.39309196e-02,  2.34840047e-02, -2.65722200e-02,
        5.78014031e-02, -2.31769662e-02, -2.21782341e-03, -4.25790809e-02,
        4.33758348e-02,  1.73128825e-02,  5.11808582e-02,  6.62342180e-03,
        1.09827295e-02,  1.60269644e-02,  3.73190530e-02,  1.62753128e-02,
       -2.00608224e-02,  9.08720493e-03,  6.11928105e-02,  3.35407741e-02,
        1.31403189e-02,  1.20372633e-02, -2.69608106e-04,  3.70137058e-02,
       -3.63093391e-02, -1.85776148e-02, -6.74379170e-02,  3.67863802e-03,
        9.67009051e-04,  1.78291739e-04,  2.56229341e-02, -2.18264386e-02,
        5.24108373e-02, -4.61204909e-02,  3.80003192e-02, -9.88594443e-03,
        2.65108924e-02,  5.29911257e-02, -8.77254233e-02,  4.14107591e-02,
       -1.53129054e-02,  3.78431976e-02,  4.48389305e-03,  2.00588629e-02,
        4.33757566e-02, -3.89885018e-03,  1.49652148e-02,  3.42622697e-02,
        8.82779881e-02,  6.77711740e-02, -2.45942809e-02, -3.65548730e-02,
        6.12730496e-02, -3.08189038e-02,  7.30511919e-02, -1.25620998e-02,
        6.96508661e-02,  6.25894777e-03, -2.56795771e-02, -6.10053241e-02,
        2.37818193e-02, -1.54884602e-03, -5.09342551e-03,  4.07995991e-02,
       -2.88566272e-03, -4.93524782e-02, -7.99814798e-03, -1.11500388e-02,
       -1.27934245e-02, -6.38431869e-03,  2.68242713e-02, -4.12516557e-02,
       -7.70272240e-02, -5.12104332e-02, -4.37586382e-02, -1.04937246e-02,
        2.78732851e-02,  3.77619937e-02,  1.11997302e-04, -1.63361605e-04,
        3.20904143e-02,  1.85359386e-03,  1.73687227e-02,  2.02511773e-02,
        3.87015939e-02,  4.69964668e-02,  7.06837745e-03, -1.53896017e-02,
        3.83843780e-02,  1.82587951e-02,  8.07617158e-02,  2.11849790e-02,
       -4.35731746e-02,  2.75316485e-03, -1.65833943e-02,  1.05832340e-02,
       -1.16247544e-02,  1.10882018e-02, -6.67151958e-02,  5.32311127e-02,
       -7.29779759e-03,  5.02478331e-02,  3.28215063e-02,  5.99595346e-03,
        5.10855764e-03,  5.41802458e-02,  4.40411568e-02,  9.56951361e-03,
        1.31994635e-02, -6.61898628e-02,  1.17897596e-02, -5.43368310e-02,
       -3.56907994e-02, -2.29847785e-02,  8.32246169e-02, -4.03813384e-02,
        3.64043604e-04, -3.47504504e-02, -2.53482293e-02, -1.85571369e-02,
        7.23665068e-03,  5.12972809e-02,  7.44101452e-03, -2.35063117e-02,
        3.90783101e-02, -8.38233978e-02,  1.06785977e-02, -1.42436260e-02,
        3.32151703e-03,  4.89875712e-02, -2.98313145e-03,  2.11491603e-02,
       -7.76958689e-02, -3.58309373e-02,  6.79254252e-03,  2.78326217e-02,
       -4.55290936e-02, -2.27491483e-02, -3.27389315e-02, -2.59030629e-02,
       -2.71916017e-02,  1.93905756e-02, -2.77752634e-02, -6.50809892e-03,
       -3.17872986e-02, -5.45185022e-02,  5.27942069e-02, -2.46965066e-02,
        5.97508289e-02,  2.49942616e-02, -2.01824252e-04, -8.15613195e-03,
       -1.31147532e-02, -2.36302596e-02, -3.35359089e-02, -2.13139802e-02,
        6.04266953e-03, -2.94151641e-02, -1.96912020e-04, -4.34243865e-03,
        3.67864072e-02,  7.84293786e-02,  1.04701435e-02,  2.63074841e-02,
       -5.32106012e-02, -2.42158510e-02, -2.08491310e-02, -1.21672088e-02,
       -2.57739853e-02,  7.50013115e-03,  2.47466117e-02, -2.19376478e-02,
       -4.05399986e-02, -3.56194042e-02,  2.18952093e-02,  7.40070567e-02,
       -2.62951814e-02,  2.95249652e-02, -1.40555091e-02, -1.31587386e-02,
       -1.30445808e-02,  6.36960641e-02,  4.44610901e-02,  9.43738781e-03,
        9.13236104e-03, -5.21891937e-02, -2.70739961e-02,  1.20914634e-02,
        3.94422561e-02,  1.07376836e-02, -7.69523671e-03, -8.67366269e-02,
        1.05033778e-02, -4.11786325e-02, -6.46248553e-03, -3.13240439e-02,
       -1.56886615e-02, -2.46288814e-02,  3.80284302e-02,  3.12870531e-03,
        2.65843654e-03, -5.95781021e-02,  1.05643552e-02, -1.10740289e-02,
       -4.58593145e-02,  7.28320479e-02,  9.22439620e-03,  1.73788033e-02,
        5.17023588e-03,  7.85920247e-02,  6.84212148e-02, -4.29486530e-03,
        2.67338357e-03, -2.78315842e-02,  4.74391468e-02,  4.43159901e-02,
       -6.23861291e-02,  3.12400591e-02, -5.78781590e-03, -2.03752667e-02,
       -1.41993640e-02,  1.15829319e-01,  4.76790518e-02,  2.05235630e-02,
        1.22058094e-02, -4.32285592e-02,  5.56067079e-02, -1.21648237e-02,
       -1.01033440e-02,  2.31208950e-02,  8.37413780e-03, -2.49590562e-03,
        2.46484857e-02, -4.19790559e-02, -9.70859081e-03,  2.28158087e-02,
       -2.80747823e-02, -4.06241836e-03, -3.36604863e-02,  3.46590504e-02,
       -3.57820392e-02,  4.19082046e-02,  7.11739212e-02, -1.82584096e-02,
       -7.71612301e-03, -1.78778470e-02, -3.81186679e-02, -2.24683769e-02,
        8.21827911e-03, -1.15735838e-02,  3.64855379e-02,  2.10262351e-02,
       -4.82981838e-02,  4.11215536e-02, -4.75677401e-02,  5.42184338e-03,
        3.65562253e-02,  2.59356182e-02,  6.31721839e-02,  1.13946188e-03,
       -8.56018532e-03,  2.04604622e-02,  3.79772782e-02, -3.44719924e-02,
       -6.93470612e-02, -2.48561031e-03, -4.43048961e-02,  9.28099174e-03,
       -8.36522086e-04,  4.94414568e-02,  6.73638424e-03, -4.31314372e-02,
       -4.21819985e-02, -5.35267591e-02, -1.79653279e-02,  3.94173869e-04,
        4.10128534e-02,  6.99797319e-03, -2.72621512e-02, -1.58520713e-02,
        3.50984223e-02,  4.35617345e-04, -7.61363702e-03,  3.46485265e-02,
       -8.27432144e-03,  3.87216695e-02, -3.49059366e-02, -3.62086482e-02,
        1.90032981e-02, -1.63268615e-02, -5.84552921e-02, -2.69239768e-03,
       -2.90117785e-03, -1.24079846e-02, -7.79166445e-02, -5.33904955e-02,
        2.84947548e-02, -1.19604133e-02, -1.61355808e-02, -3.41926254e-02,
       -2.91372314e-02,  3.85896079e-02, -7.78126251e-03,  3.82714625e-03,
       -1.44131584e-02, -3.29374261e-02, -8.19476438e-04,  3.52457017e-02,
       -6.62866887e-03,  1.27968909e-02,  1.00141214e-02,  1.79853179e-02,
        3.66008328e-03,  4.51488122e-02,  1.10000549e-02,  2.66418010e-02,
       -1.39257079e-03,  2.07740106e-02,  4.15874757e-02, -9.31280106e-03,
       -1.75612606e-02,  2.96003036e-02, -1.97837576e-02,  6.38765246e-02,
       -4.49522249e-02, -8.08738396e-02, -3.71875688e-02,  5.38517274e-02,
       -2.10619122e-02, -4.18698136e-03,  1.39370775e-02,  2.50897948e-02,
       -3.02634723e-02, -9.19288862e-03,  6.20972030e-02, -5.63268317e-03,
        3.50704193e-02, -5.25566749e-03,  5.61773777e-04, -3.66542526e-02,
        1.17002204e-02, -1.59814842e-02, -3.10059506e-02, -3.57608013e-02,
        7.98953101e-02, -1.72522310e-02,  3.98631990e-02, -4.08485765e-03,
        7.88463950e-02, -4.55726720e-02,  1.65651999e-02, -1.52410306e-02,
        8.66221711e-02, -1.07602393e-02, -6.32087281e-03, -1.58954952e-02,
        6.94929855e-04,  6.87552467e-02, -1.08827287e-02, -1.60476621e-02,
        3.15945521e-02,  4.53006364e-02,  6.50057988e-03, -2.54391739e-03,
        2.46753879e-02, -3.88229415e-02,  1.35788007e-03,  4.38260436e-02,
       -1.81854311e-02,  4.26213667e-02, -1.68059915e-02,  2.91396789e-02,
        3.33169065e-02, -3.95336635e-02,  3.20037603e-02, -4.10306817e-33,
       -9.40255169e-03,  1.54955341e-02, -3.73324379e-02, -2.12349556e-02,
       -1.19083099e-01, -2.64739078e-02,  1.34165678e-02,  4.32296954e-02,
        4.96462919e-02,  3.50567065e-02,  1.46672130e-02, -4.16799560e-02,
       -5.97170135e-03,  8.20814352e-03,  2.82650278e-03, -1.67291947e-02,
       -1.68637075e-02,  1.26348687e-02,  2.99466420e-02,  1.35795651e-02,
        3.36633041e-03,  2.98814159e-02,  2.39085648e-02,  3.11082555e-03,
       -6.31233230e-02,  5.73648363e-02,  2.80032284e-03,  3.47828269e-02,
        3.79621387e-02,  9.73844007e-02,  1.87033750e-02,  2.68479735e-02,
        2.76821535e-02, -3.69769819e-02,  3.69623192e-02, -9.17826891e-02,
       -1.09134533e-03,  3.66132222e-02,  8.25368706e-03, -9.24534816e-03,
        2.71602459e-02,  1.88423470e-02,  5.72227091e-02, -5.52229285e-02,
       -1.90644786e-02,  1.86624154e-02, -3.22454907e-02,  1.02191074e-02,
       -3.61164026e-02, -3.10763554e-03, -2.36682352e-02, -5.01986453e-03,
        2.83051431e-02, -1.48146478e-02,  2.32133884e-02, -3.60528678e-02,
        8.39456264e-03,  1.98018309e-02, -7.40007758e-02,  4.65516411e-02,
       -2.98803151e-02, -1.78952888e-02, -7.37468433e-03, -1.34979356e-02,
        4.16927179e-03,  2.58718971e-02,  8.51403326e-02, -7.21677542e-02,
       -1.71844997e-02, -1.21584730e-02, -2.76381839e-02, -4.23512794e-02,
        1.17417248e-02,  3.23381498e-02, -3.27025764e-02, -3.85424793e-02,
       -1.67794209e-02, -1.57406311e-02,  8.36305879e-03, -2.29700953e-02,
        2.36499310e-02,  9.27403290e-03,  1.88785009e-02,  1.14853745e-02,
        1.90339033e-02,  4.25944664e-02,  2.35249028e-02, -1.87715758e-02,
       -2.97039021e-02, -2.90098842e-02,  1.56247281e-02,  3.24160210e-03,
        1.61815807e-02, -1.69019029e-02,  1.66973155e-02, -5.32360980e-03,
       -3.17783579e-02,  3.66122983e-02,  2.24022195e-02, -6.86276099e-03,
        7.16108084e-02,  5.01705781e-02, -6.24578483e-02,  1.19923959e-02,
        4.13949117e-02,  2.93415096e-02, -9.31334868e-03, -8.97105318e-03,
       -3.46209807e-03,  2.09116042e-02,  1.96198449e-02,  1.34199217e-03,
       -4.93146963e-02,  2.23625265e-02, -1.56307369e-02, -2.93698013e-02,
        3.61418934e-03,  6.58074021e-02,  6.26903400e-03, -2.81416029e-02,
        1.39440438e-02,  1.53272757e-02, -5.93077131e-02, -7.35738361e-03,
       -3.15707028e-02,  4.75324094e-02, -2.40229927e-02, -3.93270375e-03,
       -1.13572804e-02, -4.34498489e-02, -3.57184149e-02, -8.10974650e-03,
        1.86797649e-07, -3.67198512e-02, -9.47149657e-03, -1.37397330e-02,
       -2.82213697e-03,  1.28777632e-02, -1.33327469e-02, -4.56694737e-02,
       -1.91275068e-02,  2.32670326e-02,  1.31105492e-02, -1.57574043e-02,
        7.48909563e-02, -3.97306457e-02,  1.10252406e-02,  3.44510451e-02,
       -2.38206610e-02, -2.71289330e-02, -1.23060718e-02,  3.03134769e-02,
        6.88309520e-02,  1.25681693e-02, -5.32588847e-02, -4.03837971e-02,
        1.14970366e-02, -8.62688795e-02, -9.10811499e-03, -1.09340809e-03,
        6.93568662e-02, -8.37887228e-02, -3.12552345e-03, -1.45738544e-02,
       -5.38673848e-02, -6.64344877e-02, -3.90910730e-02,  4.06539105e-02,
       -3.85900103e-02,  2.25496478e-02,  6.99892407e-03, -3.92486565e-02,
        2.34367549e-02, -6.03173077e-02,  7.14411736e-02, -7.79833049e-02,
       -4.80146855e-02,  9.06615518e-03,  2.30940264e-02,  1.10430913e-02,
       -1.98722146e-02, -4.21521347e-03,  2.05835165e-03, -8.79646465e-03,
        5.17626246e-03, -2.25807149e-02,  3.47749665e-02, -2.17635091e-02,
        4.80725542e-02,  4.22724150e-02, -3.68915964e-03, -1.56858750e-02,
       -1.34724984e-02, -3.80437672e-02,  9.74214170e-04,  2.32092943e-02,
       -2.58708745e-02, -6.01530224e-02,  5.77730238e-02, -5.15549928e-02,
        1.18147755e-34,  3.42527814e-02, -2.26038843e-02,  5.87083958e-02,
        1.92071348e-02,  3.06380950e-02, -3.33274784e-03, -3.98531705e-02,
        7.17058405e-02,  6.00561723e-02, -1.59897916e-02, -9.15841572e-03],
      dtype=float32)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

# Reshape vectors to be 2D arrays as cosine_similarity expects 2D input
vector_reshaped = vector.reshape(1, -1)
vector2_reshaped = vector2.reshape(1, -1)

# Calculate cosine similarity
similarity = cosine_similarity(vector_reshaped, vector2_reshaped)[0][0]

print(f"Similarity between vector and vector2: {similarity}")

Similarity between vector and vector2: 0.9252984523773193

# Word Embeddings Beyond LLMs

In [9]:
!pip install gensim==4.3.3

Requirement already satisfied: gensim==4.3.3 in /usr/local/lib/python3.12/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim==4.3.3) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim==4.3.3) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim==4.3.3) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim==4.3.3) (2.1.2)

In [10]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded

In [11]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

# Recommending songs by embeddings

In [12]:
import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [13]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43']

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118', '119', '120', '121', '122', '123', '50', '70', '71', '124', '17', '85', '14', '82', '48', '125', '47', '46', '72', '53', '25', '73', '4', '126', '59', '74', '20', '43', '127', '128', '129', '13', '82', '48', '130', '131', '132', '133', '134', '135', '136', '137', '59', '46', '138', '43', '20', '139', '140', '73', '57', '70', '141', '3', '1', '74', '142', '143', '144', '145', '48', '13', '25', '146', '50', '147', '126', '59', '20', '148', '149', '150', '151', '152', '56', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '60', '176', '51', '177', '178', '179', '180', '181', '182', '183', '184', '185', '57', '186', '187', '188', '189', '190', '191', '46', '192', '193', '194', '195', '196', '197', '198', '25', '199', '200', '49', '201', '100', '202', '203', '204', '205', '206', '207', '32', '208', '209', '210']

In [14]:
from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [15]:
song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

[('5634', 0.9985853433609009),
 ('2849', 0.9981250762939453),
 ('6626', 0.9966500401496887),
 ('2014', 0.9965460300445557),
 ('1922', 0.9959208369255066),
 ('3167', 0.9958561062812805),
 ('2976', 0.9956579208374023),
 ('6624', 0.9954155087471008),
 ('5586', 0.9953592419624329),
 ('11473', 0.9948761463165283)]

In [16]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object

In [17]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

                  title         artist
id
5634     Mr. Brownstone  Guns N' Roses
2849   Run To The Hills    Iron Maiden
6626           Blackout      Scorpions
2014    Youth Gone Wild       Skid Row
1922                One      Metallica

In [18]:
print_recommendations(2172)

                  title         artist
id
5634     Mr. Brownstone  Guns N' Roses
2849   Run To The Hills    Iron Maiden
6626           Blackout      Scorpions
2014    Youth Gone Wild       Skid Row
1922                One      Metallica

In [19]:
print_recommendations(842)

                                          title         artist
id
890     Knock You Down (w\/ Ne-Yo & Kanye West)    Keri Hilson
886                                   Heartless     Kanye West
453                                 Temperature      Sean Paul
11331                            Take You There  Sean Kingston
5698              Turnin' Me On (w\/ Lil Wayne)    Keri Hilson